apiVersion: v1
kind: Service
metadata:
  name: amq-headless
  namespace: amq-lease-ha
spec:
  clusterIP: None
  selector:
    app: amq
  ports:
    - name: openwire
      port: 61616
    - name: web
      port: 8161
